import ProjectDescription

let project = Project(
    name: "BudgetQuest",
    organizationName: "BudgetQuest",
    settings: .settings(
        base: [
            "DEVELOPMENT_TEAM": "REPLACE_WITH_TEAM_ID",
            "SWIFT_VERSION": "5.9"
        ],
        configurations: [
            .debug(name: "Debug"),
            .release(name: "Release")
        ]
    ),
    targets: [
        .target(
            name: "BudgetQuest",
            destinations: .iOS,
            product: .app,
            bundleId: "com.budgetquest.ios",
            deploymentTargets: .iOS("17.0"),
            infoPlist: .extendingDefault(with: [
                "CFBundleDisplayName": "BudgetQuest",
                "UILaunchScreen": [:]
            ]),
            sources: ["Sources/**"],
            resources: ["Resources/**"],
            dependencies: [
                // KMP shared framework — generated by `./gradlew :shared:assembleXCFramework`
                .xcframework(path: "../shared/build/XCFrameworks/release/shared.xcframework")
            ]
        ),
        .target(
            name: "BudgetQuestTests",
            destinations: .iOS,
            product: .unitTests,
            bundleId: "com.budgetquest.ios.tests",
            sources: ["Tests/**"],
            dependencies: [
                .target(name: "BudgetQuest")
            ]
        )
    ]
)
